services:
  db:
    image: postgres:15-alpine
    container_name: tro_go_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgrespassword}
      POSTGRES_DB: ${DB_NAME:-tro_go}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tro_go"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: motel-kafka
    ports:
      - "9092:9092"
    environment:
      # Cấu hình KRaft cho Apache Kafka chính thức
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFICIAL_IMAGE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data

  api:
    image: golang:1.24-alpine
    container_name: tro_go_api
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "go install github.com/cosmtrek/air@v1.51.0 && air -c .air.toml"
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      DATABASE_URL: "postgres://postgres:postgrespassword@db:5432/tro_go?sslmode=disable"
      DB_MAX_CONNS: 20
      KAFKA_BROKERS: "kafka:9092"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  kafka_data:
