server {
    listen 80;
    server_name motel.codetoolkit.org;

    # Chuyển tiếp các request có chữ /api/ vào container 'api'
    location / {
        # 'api' ở đây chính là tên service của bạn trong docker-compose
        proxy_pass http://api:8080;

        # Gắn kèm thông tin người gửi thật cho Backend Go biết
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}